/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author BenjZionGMoedillas
 */
public class AddCarPage extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPage
     */
    String carBrand, carModel, year,color,carType,carPlateNumber,carId;
    public AddCarPage() {
        initComponents();
    }

    public void addCar(){
     carBrand = (String)carBrandOption.getSelectedItem();
     carType = (String)carTypeOption.getSelectedItem();
     carModel = carModelField.getText();
     year = carYearField.getText();
     color = (String)carColorOption.getSelectedItem();
     carPlateNumber = carPlateNumberField.getText();
     carId = carIDField.getText();
       // DATABASE SET UP     
    try(MongoClient client = MongoClients.create("mongodb://localhost:27017")){
        
    MongoDatabase database = client.getDatabase("CRS");
    MongoCollection<Document> CarsCollection = database.getCollection("Cars");
         
    Document carEntry = new Document("carId",carId)
            .append("carBrand",carBrand)
            .append("carModel", carModel)
            .append("year",year)
            .append("color",color)
            .append("carType",carType)
            .append("plateNumber",carPlateNumber)
            .append("rented",false)
            .append("rentedUser",null) // <--- this should be userid that will have other attributes like name and contact number
            .append("rentDuration",null)
            .append("rentedString","No")
            .append("duration",""); //  <---- new addition
      
    CarsCollection.insertOne(carEntry);
    JOptionPane.showMessageDialog(null,"Car Entry Successfully Created!.");
    clearFields();
    
    } catch(Exception ex){
    ex.printStackTrace(); 
    }
    }
    
    public void clearFields(){
        carTypeOption.setSelectedIndex(0);
        carColorOption.setSelectedIndex(0);
        carBrandOption.setSelectedIndex(0);
        carTypeOption.setSelectedIndex(0);
        carModelField.setText("");
        carYearField.setText("");
        carIDField.setText("");
        carPlateNumberField.setText("");
        
    }
    
    public boolean sendUpdate(){
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carPlateNumberText = new javax.swing.JLabel();
        companyName1 = new javax.swing.JLabel();
        carTypeText = new javax.swing.JLabel();
        carBrandText = new javax.swing.JLabel();
        carTypeOption = new javax.swing.JComboBox<>();
        carBrandOption = new javax.swing.JComboBox<>();
        carYearField = new javax.swing.JTextField();
        carModelText = new javax.swing.JLabel();
        carYearText1 = new javax.swing.JLabel();
        carColorText1 = new javax.swing.JLabel();
        carModelField = new javax.swing.JTextField();
        carColorOption = new javax.swing.JComboBox<>();
        carPlateNumberField = new javax.swing.JTextField();
        carIDText = new javax.swing.JLabel();
        carIDField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        smallDoodleBackground = new javax.swing.JLabel();
        DoodleBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carPlateNumberText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carPlateNumberText.setForeground(new java.awt.Color(255, 0, 0));
        carPlateNumberText.setText("CAR PLATE NUMBER");
        add(carPlateNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 140, 40));

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName1.setForeground(new java.awt.Color(255, 0, 0));
        companyName1.setText("ADD CAR");
        add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 40));

        carTypeText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carTypeText.setForeground(new java.awt.Color(255, 0, 0));
        carTypeText.setText("CAR TYPE");
        add(carTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        carBrandText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carBrandText.setForeground(new java.awt.Color(255, 0, 0));
        carBrandText.setText("CAR BRAND");
        add(carBrandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 140, 40));

        carTypeOption.setBackground(new java.awt.Color(255, 51, 51));
        carTypeOption.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carTypeOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2-Seater", "4-Seater", "5-Seater", "6-Seater", "7-Seater", "8+ Seater" }));
        carTypeOption.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        carTypeOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeOptionActionPerformed(evt);
            }
        });
        add(carTypeOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, 40));

        carBrandOption.setBackground(new java.awt.Color(255, 51, 51));
        carBrandOption.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carBrandOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Honda", "Nissan", "Hyundai", "Kia", "Ford", "Chevrolet", "Mazda", "Volkswagen", "Mitsubishi", "Tesla", "Mercedes-Benz", "BMW", "Audi", "Lexus", "Cadillac", "Genesis", "Volvo", "Acura", "Infiniti", "LincolnLamborghini", "Ferrari", "Bentley", "Rolls-Royce", "Aston Martin", "McLaren", "Bugatti" }));
        carBrandOption.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        carBrandOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandOptionActionPerformed(evt);
            }
        });
        add(carBrandOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 240, 40));

        carYearField.setBackground(new java.awt.Color(255, 102, 102));
        carYearField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carYearFieldActionPerformed(evt);
            }
        });
        add(carYearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 240, 40));

        carModelText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carModelText.setForeground(new java.awt.Color(255, 0, 0));
        carModelText.setText("CAR MODEL");
        add(carModelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 40));

        carYearText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carYearText1.setForeground(new java.awt.Color(255, 0, 0));
        carYearText1.setText("CAR YEAR");
        add(carYearText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 140, 40));

        carColorText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carColorText1.setForeground(new java.awt.Color(255, 0, 0));
        carColorText1.setText("CAR COLOR");
        add(carColorText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 40));

        carModelField.setBackground(new java.awt.Color(255, 102, 102));
        carModelField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carModelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelFieldActionPerformed(evt);
            }
        });
        add(carModelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 40));

        carColorOption.setBackground(new java.awt.Color(255, 51, 51));
        carColorOption.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carColorOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Black", "Silver", "Gray", "Blue", "Red", "Yellow", "Green", "Pink", "Violet", "Cyan", "Orange", "Brown", "Beige / Champagne", "Maroon / Burgundy", "Gold", "Teal", "Turquoise", "Magenta", "Copper", "Bronze", "Navy Blue", "Charcoal", "Lime Green", "Tan", "Cream / Off-white", "Pearl White ", "Matte Black", "Gunmetal Gray" }));
        carColorOption.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        carColorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carColorOptionActionPerformed(evt);
            }
        });
        add(carColorOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 40));

        carPlateNumberField.setBackground(new java.awt.Color(255, 102, 102));
        carPlateNumberField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carPlateNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPlateNumberFieldActionPerformed(evt);
            }
        });
        add(carPlateNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 240, 40));

        carIDText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carIDText.setForeground(new java.awt.Color(255, 0, 0));
        carIDText.setText("CAR ID");
        add(carIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 140, 40));

        carIDField.setBackground(new java.awt.Color(255, 102, 102));
        carIDField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIDFieldActionPerformed(evt);
            }
        });
        add(carIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 240, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 250, 60));

        smallDoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(smallDoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 570));

        DoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        DoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(DoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 740, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void carTypeOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeOptionActionPerformed

    private void carBrandOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandOptionActionPerformed

    private void carColorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carColorOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColorOptionActionPerformed

    private void carPlateNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPlateNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPlateNumberFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addCar();
        System.out.printf("Button is working");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIDFieldActionPerformed

    private void carModelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelFieldActionPerformed

    private void carYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYearFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoodleBackground;
    private javax.swing.JComboBox<String> carBrandOption;
    private javax.swing.JLabel carBrandText;
    private javax.swing.JComboBox<String> carColorOption;
    private javax.swing.JLabel carColorText1;
    private javax.swing.JTextField carIDField;
    private javax.swing.JLabel carIDText;
    private javax.swing.JTextField carModelField;
    private javax.swing.JLabel carModelText;
    private javax.swing.JTextField carPlateNumberField;
    private javax.swing.JLabel carPlateNumberText;
    private javax.swing.JComboBox<String> carTypeOption;
    private javax.swing.JLabel carTypeText;
    private javax.swing.JTextField carYearField;
    private javax.swing.JLabel carYearText1;
    private javax.swing.JLabel companyName1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel smallDoodleBackground;
    // End of variables declaration//GEN-END:variables
}
