/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

/**
 *
 * @author BenjZionGMoedillas
 */
public class AddCarPage extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPage
     */
    public AddCarPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carPlateNumberText = new javax.swing.JLabel();
        companyName1 = new javax.swing.JLabel();
        carTypeText = new javax.swing.JLabel();
        carBrandText = new javax.swing.JLabel();
        carType = new javax.swing.JComboBox<>();
        carBrand = new javax.swing.JComboBox<>();
        carModelText = new javax.swing.JLabel();
        carModel = new javax.swing.JComboBox<>();
        carYearText1 = new javax.swing.JLabel();
        carYear1 = new javax.swing.JComboBox<>();
        carColorText1 = new javax.swing.JLabel();
        carColor1 = new javax.swing.JComboBox<>();
        carPlateNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carPlateNumberText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carPlateNumberText.setForeground(new java.awt.Color(255, 0, 0));
        carPlateNumberText.setText("CAR PLATE NUMBER");
        add(carPlateNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 140, 40));

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName1.setForeground(new java.awt.Color(255, 0, 0));
        companyName1.setText("ADD CAR");
        add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 40));

        carTypeText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carTypeText.setForeground(new java.awt.Color(255, 0, 0));
        carTypeText.setText("CAR TYPE");
        add(carTypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        carBrandText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carBrandText.setForeground(new java.awt.Color(255, 0, 0));
        carBrandText.setText("CAR BRAND");
        add(carBrandText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 40));

        carType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeActionPerformed(evt);
            }
        });
        add(carType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, 40));

        carBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBrandActionPerformed(evt);
            }
        });
        add(carBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 40));

        carModelText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carModelText.setForeground(new java.awt.Color(255, 0, 0));
        carModelText.setText("CAR MODEL");
        add(carModelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, 40));

        carModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carModelActionPerformed(evt);
            }
        });
        add(carModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 40));

        carYearText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carYearText1.setForeground(new java.awt.Color(255, 0, 0));
        carYearText1.setText("CAR YEAR");
        add(carYearText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 40));

        carYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carYear1ActionPerformed(evt);
            }
        });
        add(carYear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 40));

        carColorText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carColorText1.setForeground(new java.awt.Color(255, 0, 0));
        carColorText1.setText("CAR COLOR");
        add(carColorText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 40));

        carColor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carColor1ActionPerformed(evt);
            }
        });
        add(carColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 40));

        carPlateNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPlateNumberActionPerformed(evt);
            }
        });
        add(carPlateNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 240, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD CAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 250, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void carTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carTypeActionPerformed

    private void carBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBrandActionPerformed

    private void carModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carModelActionPerformed

    private void carYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carYear1ActionPerformed

    private void carColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carColor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carColor1ActionPerformed

    private void carPlateNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPlateNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPlateNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carBrand;
    private javax.swing.JLabel carBrandText;
    private javax.swing.JComboBox<String> carColor1;
    private javax.swing.JLabel carColorText1;
    private javax.swing.JComboBox<String> carModel;
    private javax.swing.JLabel carModelText;
    private javax.swing.JTextField carPlateNumber;
    private javax.swing.JLabel carPlateNumberText;
    private javax.swing.JComboBox<String> carType;
    private javax.swing.JLabel carTypeText;
    private javax.swing.JComboBox<String> carYear1;
    private javax.swing.JLabel carYearText1;
    private javax.swing.JLabel companyName1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
