/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

import java.awt.CardLayout;

/**
 *
 * @author ADMIN
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    CardLayout cardLayout;
    public MainPage() {
        initComponents();
        setTitle("SUNSET DRIVE CAR RENTAL SYSTEM");
        initCards();
        
          cardLayout=(CardLayout) jPanel1.getLayout();
          cardLayout.show(jPanel1, "addCarPage1");
          
          
    }
  
    public void initCards(){
        jPanel1.add(addCarPage1, "addCarPage1");
        jPanel1.add(removeCarPage1, "removeCarPage1");
        jPanel1.add(rentACarPage1, "rentACarPage1");
        jPanel1.add(rentalStatusPage1, "rentalStatusPage1");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperPanel = new javax.swing.JPanel();
        companyName1 = new javax.swing.JLabel();
        CarIcon = new javax.swing.JLabel();
        upShadow2 = new javax.swing.JLabel();
        upShadow1 = new javax.swing.JLabel();
        upShadow = new javax.swing.JLabel();
        SidePanel = new javax.swing.JPanel();
        companyName = new javax.swing.JLabel();
        rentACarButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        addCarButton1 = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        rentalStatusButton1 = new javax.swing.JButton();
        doodle = new javax.swing.JLabel();
        upShadow3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addCarPage1 = new com.mycompany.benjcarrentalsystem.AddCarPage();
        removeCarPage1 = new com.mycompany.benjcarrentalsystem.RemoveCarPage();
        rentACarPage1 = new com.mycompany.benjcarrentalsystem.RentACarPage();
        rentalStatusPage1 = new com.mycompany.benjcarrentalsystem.RentalStatusPage();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpperPanel.setBackground(new java.awt.Color(255, 0, 0));
        UpperPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        companyName1.setText("SUNSET DRIVE");
        UpperPanel.add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 20));

        CarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carCompanyLogo (2).png"))); // NOI18N
        UpperPanel.add(CarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, 40));

        getContentPane().add(UpperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1010, 40));

        upShadow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 370, 190));

        upShadow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 370, 190));

        upShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 350, 190));

        SidePanel.setBackground(new java.awt.Color(16, 16, 23));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName.setForeground(new java.awt.Color(255, 0, 0));
        companyName.setText("SUNSET DRIVE");
        SidePanel.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 40));

        rentACarButton.setBackground(new java.awt.Color(255, 0, 0));
        rentACarButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        rentACarButton.setForeground(new java.awt.Color(255, 255, 255));
        rentACarButton.setText("RENT A CAR");
        rentACarButton.setBorder(null);
        rentACarButton.setBorderPainted(false);
        rentACarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentACarButtonActionPerformed(evt);
            }
        });
        SidePanel.add(rentACarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 240, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carCompanyLogo (1).png"))); // NOI18N
        SidePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 190));

        addCarButton1.setBackground(new java.awt.Color(255, 0, 0));
        addCarButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        addCarButton1.setForeground(new java.awt.Color(255, 255, 255));
        addCarButton1.setText("ADD CAR");
        addCarButton1.setBorder(null);
        addCarButton1.setBorderPainted(false);
        addCarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarButton1ActionPerformed(evt);
            }
        });
        SidePanel.add(addCarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 220, 240, 50));

        deleteCarButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteCarButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        deleteCarButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteCarButton.setText("REMOVE A CAR");
        deleteCarButton.setBorder(null);
        deleteCarButton.setBorderPainted(false);
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });
        SidePanel.add(deleteCarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 240, 50));

        rentalStatusButton1.setBackground(new java.awt.Color(255, 0, 0));
        rentalStatusButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        rentalStatusButton1.setForeground(new java.awt.Color(255, 255, 255));
        rentalStatusButton1.setText("RENTAL STATUS");
        rentalStatusButton1.setBorder(null);
        rentalStatusButton1.setBorderPainted(false);
        rentalStatusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalStatusButton1ActionPerformed(evt);
            }
        });
        SidePanel.add(rentalStatusButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 240, 50));

        doodle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background doodle.png"))); // NOI18N
        SidePanel.add(doodle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 350, 630));

        upShadow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        SidePanel.add(upShadow3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 620));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel1.setLayout(new java.awt.CardLayout());

        addCarPage1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(addCarPage1, "card2");

        removeCarPage1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(removeCarPage1, "card3");

        rentACarPage1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(rentACarPage1, "card4");

        rentalStatusPage1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.add(rentalStatusPage1, "card5");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 710, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resizedbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1040, 660));

        jPanel2.setBackground(new java.awt.Color(247, 249, 226));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 650));

        setSize(new java.awt.Dimension(983, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rentACarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentACarButtonActionPerformed
        // TODO add your handling code here:
     //rentACarPage1.show(rentACarPage1);
     cardLayout.show(jPanel1,"rentACarPage1");
     
    }//GEN-LAST:event_rentACarButtonActionPerformed

    private void addCarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButton1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel1,"addCarPage1");
    }//GEN-LAST:event_addCarButton1ActionPerformed

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel1,"removeCarPage1");
    }//GEN-LAST:event_deleteCarButtonActionPerformed


    private void rentalStatusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalStatusButton1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanel1,"rentalStatusPage1");
    }//GEN-LAST:event_rentalStatusButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarIcon;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JButton addCarButton1;
    private com.mycompany.benjcarrentalsystem.AddCarPage addCarPage1;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel companyName1;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JLabel doodle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.mycompany.benjcarrentalsystem.RemoveCarPage removeCarPage1;
    private javax.swing.JButton rentACarButton;
    private com.mycompany.benjcarrentalsystem.RentACarPage rentACarPage1;
    private javax.swing.JButton rentalStatusButton1;
    private com.mycompany.benjcarrentalsystem.RentalStatusPage rentalStatusPage1;
    private javax.swing.JLabel upShadow;
    private javax.swing.JLabel upShadow1;
    private javax.swing.JLabel upShadow2;
    private javax.swing.JLabel upShadow3;
    // End of variables declaration//GEN-END:variables
}
