/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

/**
 *
 * @author ADMIN
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperPanel = new javax.swing.JPanel();
        companyName1 = new javax.swing.JLabel();
        CarIcon = new javax.swing.JLabel();
        upShadow2 = new javax.swing.JLabel();
        upShadow1 = new javax.swing.JLabel();
        upShadow = new javax.swing.JLabel();
        SidePanel = new javax.swing.JPanel();
        companyName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        doodle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpperPanel.setBackground(new java.awt.Color(255, 0, 0));
        UpperPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        companyName1.setForeground(new java.awt.Color(0, 0, 0));
        companyName1.setText("SUNSET DRIVE");
        UpperPanel.add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, 20));

        CarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carCompanyLogo (2).png"))); // NOI18N
        UpperPanel.add(CarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, 40));

        getContentPane().add(UpperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1010, 40));

        upShadow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 370, 190));

        upShadow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 370, 190));

        upShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dropShadow3.png"))); // NOI18N
        getContentPane().add(upShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 350, 190));

        SidePanel.setBackground(new java.awt.Color(16, 16, 23));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companyName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName.setForeground(new java.awt.Color(255, 0, 0));
        companyName.setText("SUNSET DRIVE");
        SidePanel.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 40));

        jButton1.setText("jButton1");
        SidePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 223, 230, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carCompanyLogo (1).png"))); // NOI18N
        SidePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 190));

        doodle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background doodle.png"))); // NOI18N
        SidePanel.add(doodle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 350, 630));

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resizedbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1040, 660));

        jPanel2.setBackground(new java.awt.Color(247, 249, 226));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 650));

        setSize(new java.awt.Dimension(983, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarIcon;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel companyName1;
    private javax.swing.JLabel doodle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel upShadow;
    private javax.swing.JLabel upShadow1;
    private javax.swing.JLabel upShadow2;
    // End of variables declaration//GEN-END:variables
}
