/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

/**
 *
 * @author BenjZionGMoedillas
 */
public class RemoveCarPage extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPage
     */
    public RemoveCarPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carSearchText = new javax.swing.JLabel();
        companyName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        carCount = new javax.swing.JLabel();
        carsTotalText = new javax.swing.JLabel();
        carListingText = new javax.swing.JLabel();
        carIdSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        removeCarButton = new javax.swing.JButton();
        smallDoodleBackground = new javax.swing.JLabel();
        DoodleBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carSearchText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carSearchText.setForeground(new java.awt.Color(255, 0, 0));
        carSearchText.setText("ENTER CAR ID NUMBER ");
        add(carSearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName1.setForeground(new java.awt.Color(255, 0, 0));
        companyName1.setText("REMOVE A CAR");
        add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 167, 570, 280));

        carCount.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carCount.setForeground(new java.awt.Color(255, 0, 0));
        carCount.setText("(car count here)\n");
        add(carCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 140, 40));

        carsTotalText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carsTotalText.setForeground(new java.awt.Color(255, 0, 0));
        carsTotalText.setText("CARS IN TOTAL :");
        add(carsTotalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 140, 40));

        carListingText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carListingText.setForeground(new java.awt.Color(255, 0, 0));
        carListingText.setText("CAR LISTINGS");
        add(carListingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 40));

        carIdSearchField.setBackground(new java.awt.Color(255, 153, 153));
        carIdSearchField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carIdSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIdSearchFieldActionPerformed(evt);
            }
        });
        add(carIdSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 40));

        searchButton.setBackground(new java.awt.Color(255, 0, 0));
        searchButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 140, 40));

        removeCarButton.setBackground(new java.awt.Color(255, 0, 0));
        removeCarButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        removeCarButton.setForeground(new java.awt.Color(255, 255, 255));
        removeCarButton.setText("REMOVE CAR");
        removeCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarButtonActionPerformed(evt);
            }
        });
        add(removeCarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 250, 60));

        smallDoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        smallDoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(smallDoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 570));

        DoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        DoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(DoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 740, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void carIdSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIdSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIdSearchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void removeCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoodleBackground;
    private javax.swing.JLabel carCount;
    private javax.swing.JTextField carIdSearchField;
    private javax.swing.JLabel carListingText;
    private javax.swing.JLabel carSearchText;
    private javax.swing.JLabel carsTotalText;
    private javax.swing.JLabel companyName1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton removeCarButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel smallDoodleBackground;
    // End of variables declaration//GEN-END:variables
}
