/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author BenjZionGMoedillas
 */
public class RemoveCarPage extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPage
     */
    String search; 
    public RemoveCarPage() {
        initComponents();
        retrieveData();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carSearchText = new javax.swing.JLabel();
        companyName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        carListingText = new javax.swing.JLabel();
        carIdSearchField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        removeCarButton1 = new javax.swing.JButton();
        smallDoodleBackground = new javax.swing.JLabel();
        DoodleBackground = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carSearchText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carSearchText.setForeground(new java.awt.Color(255, 0, 0));
        carSearchText.setText("ENTER CAR ID NUMBER ");
        add(carSearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName1.setForeground(new java.awt.Color(255, 0, 0));
        companyName1.setText("REMOVE A CAR");
        add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        table.setBackground(new java.awt.Color(255, 102, 102));
        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID ", "Car Brand", "Car Model", "Year", "Color", "Plate Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 690, 330));

        carListingText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carListingText.setForeground(new java.awt.Color(255, 0, 0));
        carListingText.setText("CAR LISTINGS");
        add(carListingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 40));

        carIdSearchField.setBackground(new java.awt.Color(255, 102, 102));
        carIdSearchField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carIdSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carIdSearchFieldActionPerformed(evt);
            }
        });
        add(carIdSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 40));

        refreshButton.setBackground(new java.awt.Color(255, 0, 0));
        refreshButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("REFRESH TABLE");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 230, 60));

        removeCarButton1.setBackground(new java.awt.Color(255, 0, 0));
        removeCarButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        removeCarButton1.setForeground(new java.awt.Color(255, 255, 255));
        removeCarButton1.setText("REMOVE CAR");
        removeCarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarButton1ActionPerformed(evt);
            }
        });
        add(removeCarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 250, 60));

        smallDoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        smallDoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(smallDoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 570));

        DoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        DoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(DoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 740, 570));
    }// </editor-fold>//GEN-END:initComponents
    // DISPLAY DATA IN TABLE
    public void retrieveData(){
    try(MongoClient client = MongoClients.create("mongodb://localhost:27017")){
        
    MongoDatabase database = client.getDatabase("CRS");
    MongoCollection<Document> CarsCollection = database.getCollection("Cars");
    
    FindIterable<Document> findIterable = CarsCollection.find();
    Iterator<Document> iterator = findIterable.iterator(); 
    while(iterator.hasNext()){
        Document document = iterator.next();
         //carIdTable = document.get("carId");
        Object[] row = {document.get("carId"),document.get("carBrand"),document.get("carModel"),
                        document.get("year"),document.get("color"),document.get("plateNumber")};
        
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.addRow(row);
        model.fireTableDataChanged();
    }   
        }catch(Exception ex){
            ex.printStackTrace();
        } 
    }
    
    //REMOVE AN OBJECT
    public void removeData(){
        search = carIdSearchField.getText();
        
    try(MongoClient client = MongoClients.create("mongodb://localhost:27017")){
        
    MongoDatabase database = client.getDatabase("CRS");
    MongoCollection<Document> CarsCollection = database.getCollection("Cars");
    
        Document document = CarsCollection.findOneAndDelete(Filters.eq("carId",search));
        DefaultTableModel model = (DefaultTableModel)table.getModel();
       //model.removeRow(ERROR);
        //model.fireTableDataChanged();
        retrieveData();
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }
    // REFRESH THE TABLE
      public void refreshTable(){
         try (MongoClient client = MongoClients.create("mongodb://localhost:27017")) {
        MongoDatabase database = client.getDatabase("CRS");
        MongoCollection<Document> CarsCollection = database.getCollection("Cars");

        FindIterable<Document> findIterable = CarsCollection.find();
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); 

        for (Document document : findIterable) {
            Object[] row = {
                document.get("carId"),
                document.get("carBrand"),
                document.get("carModel"),
                document.get("year"),
                document.get("color"),
                document.get("plateNumber")
            };
            model.addRow(row);
        }

    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
                
       
    private void carIdSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carIdSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carIdSearchFieldActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
          refreshTable();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void removeCarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"This data will be removed, are you sure you want to continue?");
        removeData();
        refreshTable();
        carIdSearchField.setText("");
    }//GEN-LAST:event_removeCarButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoodleBackground;
    private javax.swing.JTextField carIdSearchField;
    private javax.swing.JLabel carListingText;
    private javax.swing.JLabel carSearchText;
    private javax.swing.JLabel companyName1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeCarButton1;
    private javax.swing.JLabel smallDoodleBackground;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
