/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.benjcarrentalsystem;

/**
 *
 * @author BenjZionGMoedillas
 */
public class RentACarPage extends javax.swing.JPanel {

    /**
     * Creates new form AddCarPage
     */
    public RentACarPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carSearchText = new javax.swing.JLabel();
        companyName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        carSelected = new javax.swing.JLabel();
        carSearchText1 = new javax.swing.JLabel();
        statusText1 = new javax.swing.JLabel();
        carListingText1 = new javax.swing.JLabel();
        carSearchIDField = new javax.swing.JTextField();
        userIDField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        assignCarButton = new javax.swing.JButton();
        smallDoodleBackground = new javax.swing.JLabel();
        DoodleBackground = new javax.swing.JLabel();
        userSelected1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carSearchText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carSearchText.setForeground(new java.awt.Color(255, 0, 0));
        carSearchText.setText("ENTER USER ID NUMBER ");
        add(carSearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 40));

        companyName1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        companyName1.setForeground(new java.awt.Color(255, 0, 0));
        companyName1.setText("RENTING");
        add(companyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 570, 280));

        carSelected.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carSelected.setForeground(new java.awt.Color(255, 0, 0));
        carSelected.setText("[ CAR SELECTED ] ");
        add(carSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 140, 40));

        carSearchText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carSearchText1.setForeground(new java.awt.Color(255, 0, 0));
        carSearchText1.setText("ENTER CAR ID NUMBER ");
        add(carSearchText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, 40));

        statusText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        statusText1.setForeground(new java.awt.Color(255, 0, 0));
        statusText1.setText("STATUS :");
        add(statusText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 140, 40));

        carListingText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        carListingText1.setForeground(new java.awt.Color(255, 0, 0));
        carListingText1.setText("CAR LISTINGS");
        add(carListingText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        carSearchIDField.setBackground(new java.awt.Color(255, 153, 153));
        carSearchIDField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        carSearchIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carSearchIDFieldActionPerformed(evt);
            }
        });
        add(carSearchIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, 40));

        userIDField.setBackground(new java.awt.Color(255, 153, 153));
        userIDField.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        userIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDFieldActionPerformed(evt);
            }
        });
        add(userIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 240, 40));

        searchButton.setBackground(new java.awt.Color(255, 0, 0));
        searchButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 140, 40));

        assignCarButton.setBackground(new java.awt.Color(255, 0, 0));
        assignCarButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        assignCarButton.setForeground(new java.awt.Color(255, 255, 255));
        assignCarButton.setText("ASSIGN CAR TO USER");
        assignCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignCarButtonActionPerformed(evt);
            }
        });
        add(assignCarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 250, 60));

        smallDoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        smallDoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(smallDoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 570));

        DoodleBackground.setBackground(new java.awt.Color(51, 51, 51));
        DoodleBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doodle2.png"))); // NOI18N
        add(DoodleBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 740, 570));

        userSelected1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        userSelected1.setForeground(new java.awt.Color(255, 0, 0));
        userSelected1.setText("[ USER SELECTED ] ");
        add(userSelected1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void userIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void assignCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignCarButtonActionPerformed

    private void carSearchIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carSearchIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carSearchIDFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoodleBackground;
    private javax.swing.JButton assignCarButton;
    private javax.swing.JLabel carListingText1;
    private javax.swing.JTextField carSearchIDField;
    private javax.swing.JLabel carSearchText;
    private javax.swing.JLabel carSearchText1;
    private javax.swing.JLabel carSelected;
    private javax.swing.JLabel companyName1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel smallDoodleBackground;
    private javax.swing.JLabel statusText1;
    private javax.swing.JTextField userIDField;
    private javax.swing.JLabel userSelected1;
    // End of variables declaration//GEN-END:variables
}
